import type { Category, Product, ProductImage } from "../types";

const pastDate = new Date("2026-01-10T12:00:00.000Z");
const futureDate = new Date("2099-01-10T12:00:00.000Z");

export const devCategories: Category[] = [
  {
    id: "cat-example-active",
    name: "Perfumes",
    slug: "perfumes",
    description: "Fragrâncias selecionadas para a vitrine pública.",
    parentId: null,
    sortOrder: 10,
    isActive: true,
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "cat-example-inactive",
    name: "Coleções Reservadas",
    slug: "colecoes-reservadas",
    description: "Coleções administrativas fora da vitrine pública.",
    parentId: null,
    sortOrder: 20,
    isActive: false,
    createdAt: pastDate,
    updatedAt: pastDate
  }
];

function imageFor(
  productId: string,
  id: string,
  sortOrder: number,
  isCover = false,
  assetPath?: string,
  altText = "Frasco de perfume Tríade Essenza"
): ProductImage {
  return {
    id,
    productId,
    blobUrl: assetPath ?? `fixture://${productId}`,
    pathname: assetPath?.replace(/^\//, "") ?? `dev-fixtures/products/${productId}/${id}.png`,
    altText,
    sortOrder,
    isCover,
    width: assetPath ? 1024 : 900,
    height: assetPath ? 1024 : 1100,
    sizeBytes: 120000,
    contentType: "image/png",
    createdAt: pastDate
  };
}

export const devProducts: Product[] = [
  {
    id: "prod-example-published",
    name: "Essenza Gold",
    slug: "essenza-gold",
    shortDescription: "Âmbar dourado, especiarias suaves e rastro envolvente.",
    description:
      "Uma fragrância de presença luminosa, criada para noites especiais e assinaturas marcantes.",
    brand: "Tríade Essenza",
    inspirationName: "Gold Edition",
    gender: "unissex",
    concentration: "Eau de Parfum",
    volumeMl: 100,
    sku: "DEV-PUBLISHED-001",
    priceCents: 15990,
    compareAtPriceCents: 18990,
    costPriceCents: null,
    stockQuantity: 8,
    lowStockThreshold: 2,
    status: "published",
    isFeatured: true,
    publishedAt: pastDate,
    seoTitle: "Essenza Gold",
    seoDescription: "Perfume Essenza Gold da Tríade Essenza Parfum.",
    categories: [devCategories[0]],
    images: [
      imageFor(
        "prod-example-published",
        "img-published-cover",
        10,
        true,
        "/brand/triade-product-essenza-gold.png",
        "Frasco verde escuro do perfume Essenza Gold"
      )
    ],
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "prod-example-amber-imperial",
    name: "Amber Imperial",
    slug: "amber-imperial",
    shortDescription: "Âmbar intenso, especiarias quentes e elegância noturna.",
    description: "Perfume de rastro envolvente para momentos marcantes ao anoitecer.",
    brand: "Tríade Essenza",
    inspirationName: null,
    gender: "unissex",
    concentration: "Eau de Parfum",
    volumeMl: 50,
    sku: "DEV-PUBLISHED-002",
    priceCents: 17990,
    compareAtPriceCents: 21990,
    costPriceCents: null,
    stockQuantity: 6,
    lowStockThreshold: 2,
    status: "published",
    isFeatured: true,
    publishedAt: pastDate,
    seoTitle: null,
    seoDescription: null,
    categories: [devCategories[0]],
    images: [
      imageFor(
        "prod-example-amber-imperial",
        "img-amber-cover",
        10,
        true,
        "/brand/triade-product-amber-nuit.png",
        "Frasco âmbar do perfume Amber Imperial"
      )
    ],
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "prod-example-noir-absolu",
    name: "Noir Absolu",
    slug: "noir-absolu",
    shortDescription: "Madeiras escuras, couro suave e presença sofisticada.",
    description: "Uma assinatura intensa com acabamento seco, elegante e memorável.",
    brand: "Tríade Essenza",
    inspirationName: null,
    gender: "unissex",
    concentration: "Eau de Parfum",
    volumeMl: 100,
    sku: "DEV-PUBLISHED-003",
    priceCents: 18990,
    compareAtPriceCents: 22990,
    costPriceCents: null,
    stockQuantity: 7,
    lowStockThreshold: 1,
    status: "published",
    isFeatured: true,
    publishedAt: pastDate,
    seoTitle: null,
    seoDescription: null,
    categories: [devCategories[0]],
    images: [
      imageFor(
        "prod-example-noir-absolu",
        "img-noir-cover",
        10,
        true,
        "/brand/triade-product-noir-absolu.png",
        "Frasco preto fosco do perfume Noir Absolu"
      )
    ],
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "prod-example-out-of-stock",
    name: "Amber Nuit",
    slug: "amber-nuit",
    shortDescription: "Notas ambaradas e toque oriental para uma assinatura noturna.",
    description: "Produto reservado fora da vitrine enquanto não houver estoque disponível.",
    brand: "Tríade Essenza",
    inspirationName: null,
    gender: "nao_informado",
    concentration: null,
    volumeMl: 50,
    sku: "DEV-OOS-001",
    priceCents: 12990,
    compareAtPriceCents: null,
    costPriceCents: null,
    stockQuantity: 0,
    lowStockThreshold: 2,
    status: "published",
    isFeatured: false,
    publishedAt: pastDate,
    seoTitle: null,
    seoDescription: null,
    categories: [devCategories[0]],
    images: [imageFor("prod-example-out-of-stock", "img-oos", 10, true)],
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "prod-example-future",
    name: "Oud Royal",
    slug: "oud-royal",
    shortDescription: "Madeira oud, baunilha escura e sofisticação intensa.",
    description: "Lançamento reservado para publicação futura.",
    brand: "Tríade Essenza",
    inspirationName: null,
    gender: "nao_informado",
    concentration: null,
    volumeMl: null,
    sku: "DEV-FUTURE-001",
    priceCents: 9900,
    compareAtPriceCents: null,
    costPriceCents: null,
    stockQuantity: 5,
    lowStockThreshold: 1,
    status: "published",
    isFeatured: false,
    publishedAt: futureDate,
    seoTitle: null,
    seoDescription: null,
    categories: [devCategories[0]],
    images: [],
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "prod-example-draft",
    name: "Rose Sultan",
    slug: "rose-sultan",
    shortDescription: "Rosa oriental em preparação para curadoria.",
    description: "Produto em rascunho administrativo, fora da vitrine pública.",
    brand: "Tríade Essenza",
    inspirationName: null,
    gender: "nao_informado",
    concentration: null,
    volumeMl: null,
    sku: "DEV-DRAFT-001",
    priceCents: 9900,
    compareAtPriceCents: null,
    costPriceCents: null,
    stockQuantity: 4,
    lowStockThreshold: 1,
    status: "draft",
    isFeatured: false,
    publishedAt: pastDate,
    seoTitle: null,
    seoDescription: null,
    categories: [devCategories[0]],
    images: [],
    createdAt: pastDate,
    updatedAt: pastDate
  },
  {
    id: "prod-example-inactive",
    name: "Noir Archive",
    slug: "noir-archive",
    shortDescription: "Acorde amadeirado reservado para arquivo de coleção.",
    description:
      "Produto arquivado e indisponível para a vitrine pública.",
    brand: "Tríade Essenza",
    inspirationName: null,
    gender: "nao_informado",
    concentration: null,
    volumeMl: null,
    sku: "DEV-INACTIVE-001",
    priceCents: 9900,
    compareAtPriceCents: null,
    costPriceCents: null,
    stockQuantity: 3,
    lowStockThreshold: 1,
    status: "inactive",
    isFeatured: false,
    publishedAt: pastDate,
    seoTitle: null,
    seoDescription: null,
    categories: [devCategories[1]],
    images: [],
    createdAt: pastDate,
    updatedAt: pastDate
  }
];
